### ISSUE TITLE
running pacbio-util using qsub

### ISSUE THREAD

**Issue by corbijonathan** [douglasgscofield/PacBio-utilities#1]
Hi all, 

Thanks for the tools, seems great! 
I am having an issue running pacbio-util on a cluster using qsub... It seems that pacbio-util is running, creating a target.txt file but containing only one line indicating the path to my assembly, but no list of the indels... 
The only message I get is:
isdigit is not a valid POSIX macro at pacbio-util line 247

The command line I enter is: 
pacbio-util indel-targets --fasta /Path_to/assembly.fasta /Path_to/illumina.aln_sorted.bam > targets.txt

If I type this command in the terminal, I do get the indels in the target file but with these lines in the terminal:
Calling POSIX::isdigit() is deprecated at pacbio-util line 247, <PILEUP> line 1.
Use of uninitialized value in string eq at pacbio-util line 83, <PILEUP> line 251675.
Use of uninitialized value in string eq at pacbio-util line 83, <PILEUP> line 281153.
etc...

Any thoughts?

Thanks!

**Comment by douglasgscofield** [comment]
Thanks for your message.  I've [just pushed a commit](https://github.com/douglasgscofield/PacBio-utilities/commit/337c5a51465ad56f32d1280eb6455abda2df4f3a) to replace the use of isdigit() with an equivalent check of a regexp.

It is curious that yours works, with warning, at the command line but not via qsub.  Because isdigit() was not actually removed until perl 5.24, it might be that 'perl -v' on the command line returns an older version than 'perl -v' when run when under qsub.

In any event, this commit should take care of it.

**Comment by douglasgscofield** [comment]
Oops, spoke too soon, fixed a typo in the regexp and pushed a [new commit](https://github.com/douglasgscofield/PacBio-utilities/commit/4187bb68028a9381be8821f673a29a8ae759461d)

**Comment by corbijonathan** [comment]
seems to work perfectly, thanks so much!
