### ISSUE TITLE
-f and target assembly do not match

### ISSUE THREAD

**Issue by corbijonathan** [douglasgscofield/PacBio-utilities#2]
Hi all and Dr Scofield, 

As the first step seemed to run perfectly, I am encountering a new issue using indel-apply option. I used the same assembly to build the target file, but I receive this message:
./pacbio-util indel-apply: *** Warning: -f and target assembly do not match

It creates a new file (slightly bigger). To check if corrections were applied, I run the indel-target on this supposably corrected assembly but it produces the exact same targets. So, I guess no correction was applied. 

Am I missing something?

Thanks in advance for any help,

Jonathan

**Comment by douglasgscofield** [comment]
Hi, that message is generated if the filename of the assembly in the first line of the targets file:

    #assembly:filename

does not match the filename given with the `-f` option for `pacbio-util indel-apply`.  Did you provide the exact same filename for the `-f` option for both the `indel-targets` and `indel-apply` commands?

The first line of the targets file encodes the filename so it's not necessary to provide the `-f` option for `indel-apply` if the reference file location hasn't changed.  A mismatch generates a warning and not an error because while it might represent an error by the user, if a different reference file is used for the two commands, it is not a thorough check, because it doesn't use something like a checksum to verify the reference file *contents* are identical, which is what is really required for the commands to function in tandem correctly.
